# Generated by Django 3.2.18 on 2023-04-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('author',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-pk',)},
        ),
    ]
