# Generated by Django 3.2.18 on 2023-04-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230421_1651'),
        ('users', '0002_auto_20230428_1132'),
    ]

    operations = [
    ]
