# Generated by Django 3.2.18 on 2023-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20230417_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='cocking_time',
            new_name='cooking_time',
        ),
        migrations.AddField(
            model_name='receipt',
            name='text',
            field=models.TextField(null=True, verbose_name='Описание рецепта'),
        ),
    ]
