# Generated by Django 3.2.18 on 2023-04-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_auto_20230418_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='description',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='picture',
        ),
    ]
