# Generated by Django 3.2.18 on 2023-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_auto_20230419_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('recipe',)},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('recipe',)},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('recipe',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipes/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
    ]
